//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hasla
    {
        public System.Guid HasloID { get; set; }
        public int Iteracje { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }
        public string Haslo { get; set; }
    }
}
