//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorie
    {
        public int KategoriaID { get; set; }
        public string KategoriaKod { get; set; }
        public string KategoriaNazwa { get; set; }
    }
}
