//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przedmioty
    {
        public System.Guid PrzedmiotID { get; set; }
        public int KategoriaID { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public string Obrazek { get; set; }
        public decimal Cena { get; set; }
    }
}
