//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SzczegolyZamownienia
    {
        public int SzczegolyZamownieniaID { get; set; }
        public string ZamownienieID { get; set; }
        public string PrzedmiotID { get; set; }
        public decimal Ilosc { get; set; }
        public decimal Cena { get; set; }
        public decimal Calosc { get; set; }
    }
}
