//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public System.Guid UzytkownikID { get; set; }
        public string Mail { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Telefon { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public bool CzyKonto { get; set; }
        public string Haslo { get; set; }
        public Nullable<bool> CzyAdmin { get; set; }
    }
}
