//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        public string ZamowienieID { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<System.Guid> UzytkownikID { get; set; }
        public Nullable<bool> CzyZrealizowano { get; set; }
    }
}
